# ????????? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/telegram_bot_db
spring.datasource.username=telegram_bot_user
spring.datasource.password=qwerty123

# ????? ????
telegram.bot.token=8478395533:AAHKMY8CfGCSusLLc99L9AGVZJ4UE8OgJ9E

# ?????????????? ????????? JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
